### PR TITLE
BUG: Use correct pinning template for run_exports

### PR DESCRIPTION
**Pull request by carterbox**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by carterbox** [comment]
@conda-forge-admin, please rerender

**Comment by teake** [comment]
@carterbox Just for my education, why is the current recipe wrong? I thought that `{{ pin_compatible('cpl', max_pin='x') }}` would allow packages build against e.g. cpl 7.2.1 to also use e.g. 7.3.0 as a runtime dependency. Also, isn't `pin_subpackage` for subpackages? The current recipe doesn't have any.

**Comment by hugobuddel** [comment]
It seems other packages also use `pin_subpackage` instead of `pin_compatible`:

* libpng: https://github.com/conda-forge/libpng-feedstock/blob/main/recipe/meta.yaml
* numpy: https://github.com/conda-forge/numpy-feedstock/commit/bca09161e46d1a986e061e4aaf6a21d8eb809a98
* log4cxx: https://github.com/conda-forge/log4cxx-feedstock/issues/7
* bzip2 https://github.com/conda-forge/bzip2-feedstock/issues/7#issuecomment-454453554

The bzip2 issue contains a minimal amount of discussion about what to use:

> > Hm, shouldn't we do a `pin_compatible` instead of `pin_subpackage` in [`run_exports`](https://github.com/conda-forge/bzip2-feedstock/blob/1732d1f9a2e2819465fed384dc4fd7bb24efd83c/recipe/meta.yaml#L19)?
> 
> No the current usage of `pin_subpackage` is correct. `pin_compatible` is most often used in the `requirements/run` section of package.

So this change is probably correct, but I don't understand it. I guess that `pin_compatible` is only to be used for dependencies of the package, and `pin_subpackage` when the package itself is used as a dependency, even if there is only a single output.

**Comment by carterbox** [comment]
I haven't any doc citations, but recently I realized that `pin_compatible` only works in the requirements sections when you are pinning relative to another already mentioned dependency. If you use `pin_compatible` outside this section, the template only lists the name with no version constraints. You can verify this by looking in the conda package info/ directory. `pin_subpackage` is the correct template because there is an implied outputs section with one output.

**Comment by teake** [comment]
Ok thanks for the explanation! I'll inspect the package metadata afterwards to further convince myself :)

**Comment by teake** [comment]
Indeed, the new build has `cpl >=7.2.2,<8.0a0` for `build.run_exports` in `info/recipe/meta.yaml`, whereas the old build only had `cpl`.

**Pull request merged**
